"""
A rigorous per-path lower bound on a network (closes the 'discrete parallel law' gap).

Unit reactive current on the network:  J*_e = c_e (q_j - q_i)+ / C.   Flow decomposition: J* = sum_p w_p 1_p over q-monotone paths A -> B.
Trial flows  J = sum_p alpha_p w_p 1_p  with sum_p alpha_p w_p = 1 are admissible in Thomson's principle for the perturbed network.
Cauchy-Schwarz on every edge:  (sum_{p ∋ e} alpha_p w_p)^2 <= J*_e * sum_{p ∋ e} alpha_p^2 w_p ,  hence
        1/C_hat <= (1/C) sum_p alpha_p^2 w_p m_p ,      m_p = sum_{e in p} e^{+dV_e} (q_j - q_i)      (the per-path integral of e^{dV} dq)
and optimising alpha:                C_hat / C  >=  sum_p w_p / m_p  =  E_{p ~ current}[ 1 / m_p ].
Paths distributed as the flow decomposition are generated by the Markov chain  P(i -> j) = J+_ij / sum_j J+_ij  started on the A-boundary ∝ outflow.
"""
import numpy as np
from numba import njit
import twochannel_blindspot as t, tube_bounds as tb


@njit(cache=True)
def sample_paths(indptr, nbr, cum, qv, dve_p, dve_m, start_nodes, start_cum, inB, npaths, seed):
    np.random.seed(seed)
    mp = np.empty(npaths); mm = np.empty(npaths)
    for k in range(npaths):
        i = start_nodes[np.searchsorted(start_cum, np.random.rand())]
        a = 0.0; b = 0.0
        while not inB[i]:
            lo, hi = indptr[i], indptr[i + 1]
            e = lo + np.searchsorted(cum[lo:hi], np.random.rand())
            if e >= hi: e = hi - 1
            j = nbr[e]; dq = qv[j] - qv[i]
            a += dve_p[e] * dq; b += dve_m[e] * dq; i = j
        mp[k] = a; mm[k] = b
    return mp, mm


if __name__ == "__main__":
    N = t.N; V = t.true_potential()
    inA = ((V < 2.0) & (t.X < 0)).ravel(); inB = ((V < 2.0) & (t.X > 0)).ravel()
    c = tb.network(V); C, q = tb.capacity(c, inA, inB)
    # directed effective current
    I = np.r_[tb.EI, tb.EJ]; J = np.r_[tb.EJ, tb.EI]; cc = np.r_[c, c]
    Jp = cc * np.maximum(q[J] - q[I], 0.0); keep = Jp > 0
    I, J, Jp = I[keep], J[keep], Jp[keep]; order = np.argsort(I, kind="stable"); I, J, Jp = I[order], J[order], Jp[order]
    indptr = np.zeros(N * N + 1, dtype=np.int64); np.add.at(indptr, I + 1, 1); indptr = np.cumsum(indptr)
    out = np.bincount(I, Jp, N * N); cum = np.empty_like(Jp)
    for i in np.unique(I):
        lo, hi = indptr[i], indptr[i + 1]; cum[lo:hi] = np.cumsum(Jp[lo:hi]) / out[i]
    sA = np.where(inA & (out > 0))[0]; start_cum = np.cumsum(out[sA]) / out[sA].sum()
    rows = []
    print("ln(C_hat/C):  block seed | frozen lower | PER-PATH lower (20000 current-sampled paths) | exact | series upper | frozen upper")
    for block in (1, 3, 6, 9, 12, 18):
        for seed in (1, 2, 3):
            t.BLOCK = float(block); t.rng = np.random.default_rng(seed); dV = t.initial_error().ravel()
            de = 0.5 * (dV[I] + dV[J])
            mp, mm = sample_paths(indptr, J, cum, q, np.exp(de), np.exp(-de), sA, start_cum, inB, 20000, 7 + seed)
            Ch, _ = tb.capacity(tb.network(V + dV.reshape(N, N)), inA, inB); ex = np.log(Ch * np.exp(-((V.ravel() + dV).min() - V.min())) / C)
            b = tb.bounds(c, q, dV.reshape(N, N), 16, 48)
            lo_path = np.log(np.mean(1 / mp)); se = np.std(1 / mp) / np.sqrt(len(mp)) / np.mean(1 / mp)
            rows.append((block, seed, b[0], lo_path, se, ex, b[2], b[3], -np.log(mp.mean()), np.log(mm.mean())))
            if seed == 1:
                print(f"            {block:5d} {seed:4d} |  {b[0]:+8.3f}    |   {lo_path:+8.3f} +- {se:.3f}                     | {ex:+.3f} |  {b[2]:+8.3f}    | {b[3]:+8.3f}")
    R = np.array(rows)
    print(f"\n18 cases: per-path bound <= exact in {np.sum(R[:,3] <= R[:,5] + 2*R[:,4])}/18 (allowing 2 s.e. of sampling noise);  max (bound - exact) = {(R[:,3]-R[:,5]).max():+.4f}")
    print(f"gap exact - per-path bound: median {np.median(R[:,5]-R[:,3]):.3f}, max {(R[:,5]-R[:,3]).max():.3f}   [frozen bound: median {np.median(R[:,5]-R[:,2]):.3f}, max {(R[:,5]-R[:,2]).max():.3f}]")
    print(f"consistency: path means reproduce the frozen bounds, max |diff| = {np.abs(R[:,8]-R[:,2]).max():.3f} (lower), {np.abs(R[:,9]-R[:,7]).max():.3f} (upper)")
    np.savetxt("data/path_bound_2d.csv", R, delimiter=",", comments="", header="block_kT,seed,frozen_lower,per_path_lower,per_path_se,exact,series_upper,frozen_upper,frozen_lower_from_paths,frozen_upper_from_paths")
